/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Vector;
/**
 *
 * @author ashle
 */
public class project extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "mysqldbms04";
    private static final String HomeInterior = "jdbc:mysql://localhost:3306/home";
    
    Connection p = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    int q, i, id, deleteItem;
    
    public project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //============================================Function====================================
    public void upDateDB()
    {
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            p = DriverManager.getConnection(HomeInterior,username,password);
            pst = p.prepareStatement("select * from project");
            
            rs = pst.executeQuery();
            ResultSetMetaData dData = rs.getMetaData();
            
            q = dData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()) {
                Vector columnData = new Vector();
                
                for(i = 1;i <= q; i++)
                {
                    columnData.add(rs.getString("id"));
                    columnData.add(rs.getString("PROJECT_ID"));
                    columnData.add(rs.getString("CLIENT_ID"));
                    columnData.add(rs.getString("SUPPLIER_ID"));
                    columnData.add(rs.getString("PROJECT_NAME"));
                    columnData.add(rs.getString("START_DATE"));
                    columnData.add(rs.getString("END_DATE"));
                }
                RecordTable.addRow(columnData);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public class YourClassName extends javax.swing.JFrame {

    // Your other code...

    // Constructor and other methods...

    // Method for updating the table with project data
    private void updateTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Project ID");
            model.addColumn("Client ID");
            model.addColumn("Supplier ID");
            model.addColumn("Project Name");
            model.addColumn("Start Date");
            model.addColumn("End Date");
            model.addColumn("Project Status");

            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(HomeInterior, username, password);
            PreparedStatement pst = connection.prepareStatement("SELECT * FROM PROJECT");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] row = new Object[7];
                for (int i = 0; i < 7; i++) {
                    row[i] = rs.getObject(i + 1);
                }
                model.addRow(row);
            }

            jTable1.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
}

    
    //=====================================End-Function========================================
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jbtnInsert = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtPID = new javax.swing.JTextField();
        jtxtCID = new javax.swing.JTextField();
        jtxtSID = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtSDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtEDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashle\\Downloads\\home interior\\project.png")); // NOI18N
        jLabel1.setText("PROJECT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 46, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PROJECT_ID", "CLIENT_ID", "SUPPLIER_ID", "PROJECT_NAME", "START_DATE", "END_DATE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 114, 1215, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashle\\Downloads\\home interior\\close.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1489, 0, 30, 28));

        jbtnInsert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnInsert.setText("INSERT");
        jbtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(1399, 138, 101, -1));

        jbtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnUpdate.setText("UPDATE");
        getContentPane().add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1399, 225, -1, -1));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnPrint.setText("PRINT");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1399, 319, 101, -1));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnReset.setText("RESET");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1399, 408, 101, -1));

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1399, 494, 101, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Project ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Client ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Supplier ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Project Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Start Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 580, -1, -1));
        getContentPane().add(jtxtPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 119, -1));

        jtxtCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCIDActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 152, -1));

        jtxtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSIDActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 132, -1));

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, 160, -1));
        getContentPane().add(jtxtSDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, 140, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("End Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 580, -1, -1));
        getContentPane().add(jtxtEDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 630, 130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashle\\Downloads\\home interior\\ppage.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1530, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int yes = JOptionPane.showConfirmDialog(this,"Are you sure?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(yes==JOptionPane.YES_OPTION)
            new homepage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSIDActionPerformed

    private void jtxtCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCIDActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
    jtxtPID.setText("");
    jtxtCID.setText("");
    jtxtSID.setText("");
    jtxtName.setText("");
    jtxtSDate.setText("");
    jtxtEDate.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertActionPerformed
    try {
        Class.forName("com.mysql.jdbc.Driver");
        p = DriverManager.getConnection(HomeInterior, username, password);
        
        // Calculate project status based on start and end dates
        String projectStatus;
        LocalDate startDate = LocalDate.parse(jtxtSDate.getText());
        LocalDate endDate = LocalDate.parse(jtxtEDate.getText());
        LocalDate currentDate = LocalDate.now();
        
        if (startDate.isAfter(currentDate)) {
            projectStatus = "Scheduled";
        } else if (startDate.isBefore(currentDate) && endDate.isAfter(currentDate)) {
            projectStatus = "In Progress";
        } else {
            projectStatus = "Completed";
        }
        
        // Prepare and execute the insertion query
        pst = p.prepareStatement("insert into PROJECT(PROJECT_ID, CLIENT_ID, SUPPLIER_ID, PROJECT_NAME, START_DATE, END_DATE, PROJECT_STATUS) values (?, ?, ?, ?, ?, ?, ?)");
        pst.setString(1, jtxtPID.getText());
        pst.setString(2, jtxtCID.getText());
        pst.setString(3, jtxtSID.getText());
        pst.setString(4, jtxtName.getText());
        pst.setString(5, jtxtSDate.getText());
        pst.setString(6, jtxtEDate.getText());
        pst.setString(7, projectStatus);
        
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(this, "Record Added");
        upDateDB();
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_jbtnInsertActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
     DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try
        {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            
                    deleteItem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete item", "Warning",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_NO_OPTION)
            {
               Class.forName("com.mysql.jdbc.Driver");
              p = DriverManager.getConnection(HomeInterior,username,password);
              pst = p.prepareStatement("delete from project where id=?");
              
              pst.setInt(1,id);
              pst.executeUpdate();
              JOptionPane.showMessageDialog(this, "Record deleted");
             upDateDB();
             
             jtxtPID.setText("");
             jtxtCID.setText("");
             jtxtSID.setText("");
             jtxtName.setText("");
             jtxtSDate.setText("");
             jtxtEDate.setText("");
            }
        }
        catch(ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        } catch(SQLException ex) {
            System.err.println(ex);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
          int SelectedRows = jTable1.getSelectedRow();
          
          jtxtPID.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
          jtxtSID.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
          jtxtCID.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
          jtxtName.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
          jtxtSDate.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
          jtxtEDate.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
    MessageFormat header = new MessageFormat("Print in progress");
    MessageFormat footer = new MessageFormat("Page (0, number, integer)");
    
    try 
    {
        jTable1.print(JTable.PrintMode.NORMAL,header,footer);
    }
    
    catch(java.awt.print.PrinterException e)
    {
        System.err.format("No Printer Found", e.getMessage());
    }
    }//GEN-LAST:event_jbtnPrintActionPerformed
     
    
    /**
     * @param args the command line argumentsw
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnInsert;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtCID;
    private javax.swing.JTextField jtxtEDate;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPID;
    private javax.swing.JTextField jtxtSDate;
    private javax.swing.JTextField jtxtSID;
    // End of variables declaration//GEN-END:variables
}
